controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}/
    requirements:
        _locale: en|ja

default_locale_redirection:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en/
        permanent: true

kernel:
    resource: ../../src/Kernel.php
    type: annotation
